# Generate local .env for Docker prod (never commit .env).
param(
    [string]$EthRpcUrl = "",
    [string]$CorsOrigin = "https://explorer.example.com",
    [switch]$Force
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $Root

$envPath = Join-Path $Root ".env"
if ((Test-Path $envPath) -and -not $Force) {
    Write-Host ".env already exists. Re-run with -Force to overwrite, or edit .env manually." -ForegroundColor Yellow
    exit 0
}

function New-Secret([int]$Bytes = 32) {
    $buf = New-Object byte[] $Bytes
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($buf)
    return [Convert]::ToBase64String($buf).TrimEnd("=").Replace("+", "x").Replace("/", "y")
}

$jwt = New-Secret 32
$oracle = New-Secret 32
Push-Location $Root
try {
    $rpcKey = (python -c "from middleware.rpc_auth import RPCApiKeyAuth; print(RPCApiKeyAuth.generate_key())").Trim()
    if ($LASTEXITCODE -ne 0 -or -not $rpcKey) {
        throw "Failed to generate RPC API key"
    }
} finally {
    Pop-Location
}

if (-not $EthRpcUrl) {
    $EthRpcUrl = Read-Host "ETH_RPC_URL (Ethereum JSON-RPC, required for bridge)"
}
if (-not $EthRpcUrl) {
    Write-Host "ETH_RPC_URL is required for prod Docker." -ForegroundColor Red
    exit 1
}

$walletPath = Join-Path $Root "data\wallet.json"
if (-not (Test-Path $walletPath)) {
    New-Item -ItemType Directory -Force -Path (Split-Path $walletPath) | Out-Null
    Copy-Item (Join-Path $Root "docker\founder.wallet.json") $walletPath
    Write-Host "Created data\wallet.json from docker\founder.wallet.json" -ForegroundColor Green
}

$content = @"
# Generated by scripts/setup_prod_env.ps1 - DO NOT COMMIT
DEPLOYMENT_MODE=prod
JWT_SECRET=$jwt
RPC_API_KEY_REQUIRED=true
RPC_API_KEYS=$rpcKey
BRIDGE_ORACLE_SECRET=$oracle
CORS_ORIGINS=$CorsOrigin
ETH_RPC_URL=$EthRpcUrl
BRIDGE_MODE=rust
BRIDGE_REQUIRE_L1_PROOF=true
BRIDGE_PROBE_L1_RPC=false
ABS_REQUIRE_NATIVE_CRYPTO=true
"@

Set-Content -Path $envPath -Value $content -Encoding UTF8
Write-Host "Wrote $envPath" -ForegroundColor Green
Write-Host ""
Write-Host "Next:" -ForegroundColor Cyan
Write-Host "  .\scripts\docker_prod.ps1" -ForegroundColor White
Write-Host ""
Write-Host "RPC key (save it):" -ForegroundColor Gray
Write-Host "  $rpcKey" -ForegroundColor Gray
